services:
  #  client-react-vite:
  #    image: client-react-vite
  #    build:
  #      context: ./Client/
  #      dockerfile: ./Dockerfile
  #    init: true
  #    volumes:
  #      - type: bind
  #        source: ./ClientReact/
  #        target: /usr/src/app/
  #      - type: volume
  #        target: /usr/src/app/node_modules
  #      - type: bind
  #        source: ./ClientReact/vite.config.js
  #        target: /usr/src/app/vite.config.js
  #    networks:
  #      - frontend
  #    ports:
  #      - 5173:5173
  server:
    image: server
    build:
      context: ./Server/
      dockerfile: ./Dockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./Server/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    depends_on:
      - db
    env_file:
      - ./Server/.env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    networks:
      #- frontend
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./Server/.env
    # environment:
    #   POSTGRES_USER: ${POSTGRES_USER}
    #   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #   POSTGRES_DB: ${POSTGRES_DB}
    #   POSTGRES_HOST: ${POSTGRES_HOST}
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  frontend:
  backend:
    driver: bridge
